import { Product, Review } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'AeroGlide Wireless Ergonomic Mouse',
    description: 'Experience unparalleled comfort and performance with the AeroGlide Wireless Mouse. Featuring an ergonomic vertical design that reduces wrist strain, an ultra-precise 26,000 DPI optical sensor, quiet-click tactile switches, and up to 120 hours of battery life on a single charge. Perfect for software engineers, designers, and power users who spend hours at their desks.',
    shortDescription: 'Ergonomic vertical wireless mouse with 26k DPI sensor and silent clicks.',
    rating: 4.8,
    reviewsCount: 5,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=600&fit=crop',
    category: 'Accessories',
    price: 89.99,
  },
  {
    id: 'prod-2',
    title: 'CyberClick K95 Mechanical Keyboard',
    description: 'A premium 75% layout mechanical keyboard designed for the ultimate typing experience. Engineered with hot-swappable linear yellow switches, double-shot PBT keycaps, sound-dampening gasket mount design, and customizable per-key RGB backlighting. Crafted with a solid CNC-anodized aluminum frame, this keyboard is both robust and beautifully satisfying to type on.',
    shortDescription: 'Gasket-mounted hot-swappable 75% mechanical keyboard with aluminum frame.',
    rating: 4.6,
    reviewsCount: 4,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&h=600&fit=crop',
    category: 'Keyboards',
    price: 149.99,
  },
  {
    id: 'prod-3',
    title: 'AuraSound ANC Gen-II Headphones',
    description: 'Immerse yourself in pure high-fidelity audio with AuraSound headphones. Featuring cutting-edge hybrid active noise cancellation (ANC), custom 40mm dynamic drivers, and a plush memory foam headband. With spatial audio tracking, transparency mode, and an impressive 45-hour battery life, they redefine wireless listening comfort.',
    shortDescription: 'Premium over-ear wireless headphones with hybrid active noise cancellation.',
    rating: 4.5,
    reviewsCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop',
    category: 'Audio',
    price: 299.99,
  },
  {
    id: 'prod-4',
    title: 'VoxMini Smart Speaker & Hub',
    description: 'Small size, monumental sound. The VoxMini is a compact smart speaker that doubles as an IoT smart home hub. Powered by custom acoustic drivers for rich bass and crisp highs. It features physical privacy switches, voice assistant integration, multi-room audio sync, and a minimalist fabric cover that matches any workspace or living room.',
    shortDescription: 'Compact smart speaker with deep bass, high-fidelity sound, and IoT hub integration.',
    rating: 4.2,
    reviewsCount: 4,
    imageUrl: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&h=600&fit=crop',
    category: 'Smart Home',
    price: 59.99,
  },
  {
    id: 'prod-5',
    title: 'MagCharge 3-in-1 Power Stand',
    description: 'De-clutter your nightstand or work desk with the MagCharge Stand. Crafted from premium zinc alloy, it delivers fast wireless charging simultaneously to your smartphone, smartwatch, and wireless earbuds. Features smart thermal management, secure alignment magnets, and a sleek matte finish.',
    shortDescription: 'MagSafe compatible 3-in-1 fast wireless charging dock made of zinc alloy.',
    rating: 3.9,
    reviewsCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1622445275576-721325763afe?w=800&h=600&fit=crop',
    category: 'Charging',
    price: 79.99,
  },
  {
    id: 'prod-6',
    title: 'Merino Wool Minimalist Desk Mat',
    description: 'Elevate your desk setup with a premium desk mat crafted from 100% renewable Merino wool felt. Provides a soft, warm surface for your hands while offering smooth mouse tracking and exceptional acoustic dampening. Features an anti-slip natural cork backing to prevent sliding.',
    shortDescription: 'Eco-friendly felt wool desk mat with non-slip natural cork backing.',
    rating: 4.7,
    reviewsCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1616627988170-6c5a9eba8818?w=800&h=600&fit=crop',
    category: 'Accessories',
    price: 49.99,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userName: 'Sarah Jenkins',
    rating: 5,
    comment: 'The AeroGlide vertical mouse completely resolved my wrist pain! The shape is incredibly comfortable, and the cursor movement feels silky smooth. Battery lasts forever, highly recommended for developers!',
    createdAt: '2026-06-15T10:30:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userName: 'Alex Carter',
    rating: 4,
    comment: 'Great mouse. The build quality is excellent and the silent click buttons are fantastic for quiet environments. Deducted one star because the custom software only works on Windows, and I am on macOS.',
    createdAt: '2026-06-20T14:15:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-1',
    userName: 'Sophia Martinez',
    rating: 5,
    comment: 'Amazing ergonomics. I was skeptical about vertical mice, but after two days of use, I will never go back to a standard flat mouse. The scroll wheel feels very premium too.',
    createdAt: '2026-06-25T08:45:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-1',
    userName: 'David Kim',
    rating: 5,
    comment: 'Absolutely spectacular battery life! I have been using it for three weeks straight on a single charge and it is still at 40%. The rubberized finish feels luxurious.',
    createdAt: '2026-06-27T17:20:00Z',
  },
  {
    id: 'rev-5',
    productId: 'prod-1',
    userName: 'Emily Cooper',
    rating: 5,
    comment: 'Perfect size for medium to large hands. The DPI adjustments are quick, and the sensor never skips a beat even without a mousepad. Well worth the price.',
    createdAt: '2026-06-28T11:05:00Z',
  },
  {
    id: 'rev-6',
    productId: 'prod-2',
    userName: 'Marcus Aurelius',
    rating: 5,
    comment: 'The tactile and acoustic typing feel of the gasket mount on this K95 is second to none. Sounds like gentle raindrops. Switches are perfectly lubricated out of the box!',
    createdAt: '2026-06-10T12:00:00Z',
  },
  {
    id: 'rev-7',
    productId: 'prod-2',
    userName: 'Clara Oswald',
    rating: 4,
    comment: 'Stunning keyboard and the linear yellow switches feel incredibly smooth. The RGB lighting is customizable and looks gorgeous under the PBT keycaps. Just wish it had a physical volume dial.',
    createdAt: '2026-06-18T16:30:00Z',
  },
  {
    id: 'rev-8',
    productId: 'prod-2',
    userName: 'Jonathan Byers',
    rating: 5,
    comment: 'Heavy, stable, and absolutely beautiful CNC aluminum. Keycaps feel textured and premium. I replaced the linear switches with tactile brown ones easily since it is hot-swappable.',
    createdAt: '2026-06-22T09:12:00Z',
  },
  {
    id: 'rev-9',
    productId: 'prod-2',
    userName: 'Elena Rostova',
    rating: 4,
    comment: 'Great typing experience, and the sound profile is very clean and deep. However, it takes a few hours to get used to the 75% layout if you come from a full-sized keyboard.',
    createdAt: '2026-06-26T13:40:00Z',
  },
  {
    id: 'rev-10',
    productId: 'prod-3',
    userName: 'Michael Scott',
    rating: 5,
    comment: 'The Active Noise Cancellation is scary good! Blocks out my coworkers talking and the office AC completely. Audio quality is extremely clear and balanced, not overly bassy.',
    createdAt: '2026-06-12T15:55:00Z',
  },
  {
    id: 'rev-11',
    productId: 'prod-3',
    userName: 'Pam Beesly',
    rating: 4,
    comment: 'Very comfortable ear cups. The memory foam is soft and does not clamp too tightly on my head. Microphone is clear for Zoom calls. Docked a star because charging is a bit slow.',
    createdAt: '2026-06-19T10:05:00Z',
  },
  {
    id: 'rev-12',
    productId: 'prod-3',
    userName: 'Jim Halpert',
    rating: 4,
    comment: 'Battery life is outstanding. I get almost a full week of use out of them. The spatial audio tracking works nicely for watching movies on my tablet. Sounds premium!',
    createdAt: '2026-06-24T18:22:00Z',
  },
  {
    id: 'rev-13',
    productId: 'prod-4',
    userName: 'Gavin Belson',
    rating: 4,
    comment: 'Surprisingly punchy audio from such a small speaker. The acoustic design is well engineered. Integrates perfectly with my smart home devices. Privacy switch is a great touch.',
    createdAt: '2026-06-08T11:45:00Z',
  },
  {
    id: 'rev-14',
    productId: 'prod-4',
    userName: 'Richard Hendricks',
    rating: 4,
    comment: 'The IoT hub configuration was clean and responsive. Sound is crisp. I just wish the power cable was USB-C instead of a proprietary barrel jack.',
    createdAt: '2026-06-14T14:50:00Z',
  },
  {
    id: 'rev-15',
    productId: 'prod-4',
    userName: 'Monica Hall',
    rating: 4,
    comment: 'Aesthetically fits beautifully on my kitchen counter. The fabric cover looks very clean. Smart assistant response is quick, and the microphones pick up my voice easily.',
    createdAt: '2026-06-20T08:10:00Z',
  },
  {
    id: 'rev-16',
    productId: 'prod-4',
    userName: 'Jared Dunn',
    rating: 5,
    comment: 'I love the multi-room audio sync. I bought two of these and playing music in sync across the hallway works flawlessly. Highly recommend!',
    createdAt: '2026-06-26T20:30:00Z',
  },
  {
    id: 'rev-17',
    productId: 'prod-5',
    userName: 'Peter Gregory',
    rating: 4,
    comment: 'Magnet alignment is strong and secure for my iPhone. It charges all three of my daily devices at once. It does get a little warm when doing fast charging, but nothing alarming.',
    createdAt: '2026-06-11T13:10:00Z',
  },
  {
    id: 'rev-18',
    productId: 'prod-5',
    userName: 'Laurie Bream',
    rating: 3,
    comment: 'The stand is sturdy and looks elegant. However, fast charging for the Apple Watch is not supported. It charges at standard speed, which is a bit disappointing at this price point.',
    createdAt: '2026-06-17T09:25:00Z',
  },
  {
    id: 'rev-19',
    productId: 'prod-5',
    userName: 'Gilfoyle',
    rating: 4,
    comment: 'It does exactly what it is designed to do: charges the phone, watch, and pods. Solid metal frame prevents tipping. Looks decent on a dark desk.',
    createdAt: '2026-06-25T15:40:00Z',
  },
  {
    id: 'rev-20',
    productId: 'prod-6',
    userName: 'Dinesh Chugtai',
    rating: 5,
    comment: 'This wool felt mat looks incredibly premium! It is very thick and soft, and the non-slip cork back works perfectly. Adds a nice cozy feel to my workstation.',
    createdAt: '2026-06-13T10:15:00Z',
  },
  {
    id: 'rev-21',
    productId: 'prod-6',
    userName: 'Erlich Bachman',
    rating: 4,
    comment: 'Beautiful texture and fits my full size keyboard and mouse easily. Mouse slides smoothly enough for work, though I would not recommend it for fast-paced FPS gaming.',
    createdAt: '2026-06-21T16:50:00Z',
  },
  {
    id: 'rev-22',
    productId: 'prod-6',
    userName: 'Jian Yang',
    rating: 5,
    comment: 'Very good desk mat. Keeps desk clean. Wool is soft. Safe from scratches. I like it.',
    createdAt: '2026-06-27T11:35:00Z',
  }
];
